"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { categories, formatPrice, Product, products } from "../lib/products";

export function Header() {
  const [open, setOpen] = useState(false);
  return <header className="site-header">
    <div className="container header-row">
      <Link href="/" className="brand-mark"><span className="brand-square">P</span><span>PC<span className="brand-accent">STORE</span></span></Link>
      <nav className="desktop-nav" aria-label="Điều hướng chính"><Link href="/products">Sản phẩm</Link><a href="#categories">Danh mục</a><a href="#services">Dịch vụ</a></nav>
      <div className="header-actions"><Link href="/products" className="search-pill"><span>⌕</span><span>Tìm linh kiện, laptop...</span></Link><button className="icon-button" aria-label="Tài khoản">◯</button><button className="cart-button" aria-label="Giỏ hàng">Giỏ hàng <b>0</b></button><button className="menu-button" aria-label="Mở menu" onClick={() => setOpen(!open)}>☰</button></div>
    </div>
    {open && <nav className="mobile-nav" aria-label="Menu di động"><Link href="/products" onClick={() => setOpen(false)}>Tất cả sản phẩm</Link><a href="#categories" onClick={() => setOpen(false)}>Danh mục</a><a href="#services" onClick={() => setOpen(false)}>Dịch vụ</a></nav>}
  </header>;
}

export function Footer() { return <footer className="site-footer"><div className="container footer-grid"><div><Link href="/" className="brand-mark"><span className="brand-square">P</span><span>PC<span className="brand-accent">STORE</span></span></Link><p>Thiết bị tốt cho góc máy bạn muốn.</p></div><div><strong>Mua sắm</strong><Link href="/products">Laptop</Link><Link href="/products">Linh kiện</Link><Link href="/products">Phụ kiện</Link></div><div><strong>Hỗ trợ</strong><span>Trung tâm trợ giúp</span><span>Chính sách đổi trả</span><span>Bảo hành</span></div><div><strong>Liên hệ</strong><span>hello@pcstore.local</span><span>1900 6868</span><span>Thứ 2–7 · 8:00–18:00</span></div></div><div className="container footer-bottom">© 2025 PC Store · Giao diện đang dùng dữ liệu mẫu</div></footer>; }

function ProductVisual({ product, large = false }: { product: Product; large?: boolean }) { return <div className={`product-visual ${large ? "product-visual-large" : ""}`} style={{ "--product-accent": product.accent } as React.CSSProperties}><span className="visual-orbit" /><span className="visual-label">{product.category}</span><span className="visual-letter">{product.name.slice(0, 1)}</span><span className="visual-brand">{product.brand}</span></div>; }

export function ProductCard({ product }: { product: Product }) { return <article className="product-card"><Link href={`/products/${product.slug}`}><ProductVisual product={product} /><div className="product-card-body"><div className="product-meta"><span>{product.brand}</span>{product.badge && <span className="product-badge">{product.badge}</span>}</div><h3>{product.name}</h3><p>{product.description}</p><div className="product-price"><strong>{formatPrice(product.price)}</strong>{product.oldPrice && <del>{formatPrice(product.oldPrice)}</del>}</div><span className={product.stock === 0 ? "stock out" : "stock"}>{product.stock === 0 ? "Tạm hết hàng" : `${product.stock} sản phẩm sẵn có`}</span></div></Link></article>; }

export function HomePage() { return <><Header /><main><section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Bộ sưu tập 2025 · PC Store</span><h1>Build your <em>next</em> level.</h1><p>Những linh kiện đúng gu, hiệu năng đúng nhu cầu. Chọn từng món để tạo nên góc máy của riêng bạn.</p><div className="hero-actions"><Link className="button button-primary" href="/products">Khám phá sản phẩm <span>↗</span></Link><a className="text-link" href="#categories">Xem danh mục</a></div><div className="hero-note"><span className="signal-dot" /> Dữ liệu mẫu · Sẵn sàng để khám phá</div></div><div className="hero-art"><div className="hero-ring" /><div className="hero-chip"><span>PC</span><strong>∞</strong></div><div className="hero-spec"><span>01</span><small>Curated<br />hardware</small></div><div className="hero-floating">DESIGNED FOR<br /><b>YOUR FLOW</b></div></div></div></section><section className="container section" id="categories"><div className="section-heading"><div><span className="eyebrow">Chọn điểm bắt đầu</span><h2>Phần cứng cho mọi nhịp làm việc.</h2></div><Link className="text-link" href="/products">Xem tất cả ↗</Link></div><div className="category-grid">{categories.map((category) => <Link className={`category-tile category-${category.tone}`} href={`/products?category=${encodeURIComponent(category.name)}`} key={category.name}><span className="category-index">0{categories.indexOf(category) + 1}</span><span className="category-icon">{category.name === "Laptop" ? "▱" : category.name === "PC Gaming" ? "▣" : category.name === "Linh kiện" ? "⌘" : "◈"}</span><strong>{category.name}</strong><small>{category.count}</small><span className="tile-arrow">↗</span></Link>)}</div></section><section className="container section featured-section"><div className="section-heading"><div><span className="eyebrow">Được chọn hôm nay</span><h2>Những món đáng để nâng cấp.</h2></div><Link className="text-link" href="/products">Xem catalog ↗</Link></div><div className="product-grid">{products.filter((product) => product.featured).map((product) => <ProductCard product={product} key={product.id} />)}</div></section><section className="container services section" id="services"><div><span className="eyebrow">Mua sắm nhẹ đầu</span><h2>Từ ý tưởng đến góc máy hoàn chỉnh.</h2></div><div className="service-list"><div><span>01</span><strong>Tư vấn theo nhu cầu</strong><p>Chọn cấu hình dựa trên công việc bạn thực sự làm mỗi ngày.</p></div><div><span>02</span><strong>Đóng gói cẩn thận</strong><p>Mỗi món hàng được kiểm tra và chuẩn bị trước khi rời kho.</p></div><div><span>03</span><strong>Đồng hành dài lâu</strong><p>Hỗ trợ kỹ thuật rõ ràng, dễ hiểu sau khi bạn nhận hàng.</p></div></div></section></main><Footer /></>; }

export function CatalogPage() { const [query, setQuery] = useState(""); const [category, setCategory] = useState("Tất cả"); const [sort, setSort] = useState("featured"); const filtered = useMemo(() => products.filter((p) => (category === "Tất cả" || p.category === category) && p.name.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === "price-low" ? a.price - b.price : sort === "price-high" ? b.price - a.price : Number(Boolean(b.featured)) - Number(Boolean(a.featured))), [category, query, sort]); return <><Header /><main className="catalog-page container"><div className="catalog-hero"><span className="eyebrow">Catalog · {products.length} sản phẩm mẫu</span><h1>Chọn món tiếp theo<br /><em>cho góc máy.</em></h1><p>Duyệt qua những thiết bị được chọn kỹ cho game, sáng tạo và công việc mỗi ngày.</p></div><div className="catalog-toolbar"><label className="search-field"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm theo tên sản phẩm..." /></label><select value={category} onChange={(e) => setCategory(e.target.value)} aria-label="Lọc danh mục"><option>Tất cả</option>{categories.map((c) => <option key={c.name}>{c.name}</option>)}</select><select value={sort} onChange={(e) => setSort(e.target.value)} aria-label="Sắp xếp"><option value="featured">Ưu tiên nổi bật</option><option value="price-low">Giá thấp đến cao</option><option value="price-high">Giá cao đến thấp</option></select></div><div className="catalog-count">{filtered.length} kết quả <span>{category !== "Tất cả" ? `trong ${category}` : "trong tất cả danh mục"}</span></div>{filtered.length ? <div className="product-grid product-grid-catalog">{filtered.map((product) => <ProductCard product={product} key={product.id} />)}</div> : <div className="empty-state"><span>⌕</span><h2>Không tìm thấy sản phẩm</h2><p>Thử một từ khóa khác hoặc xóa bộ lọc để xem toàn bộ catalog.</p><button className="button button-dark" onClick={() => { setQuery(""); setCategory("Tất cả"); }}>Xóa bộ lọc</button></div>}</main><Footer /></>; }

export function ProductDetail({ product }: { product: Product }) { const [quantity, setQuantity] = useState(1); const [added, setAdded] = useState(false); return <><Header /><main className="container detail-page"><div className="breadcrumb"><Link href="/products">Catalog</Link><span>/</span><span>{product.name}</span></div><div className="detail-grid"><ProductVisual product={product} large /><div className="detail-copy"><span className="eyebrow">{product.brand} · {product.category}</span><h1>{product.name}</h1><p className="detail-description">{product.description}</p><div className="detail-price"><strong>{formatPrice(product.price)}</strong>{product.oldPrice && <del>{formatPrice(product.oldPrice)}</del>}</div><div className={product.stock === 0 ? "detail-stock out" : "detail-stock"}>{product.stock === 0 ? "Sản phẩm đang tạm hết hàng" : `Sẵn có · còn ${product.stock} sản phẩm`}</div><div className="quantity-row"><label htmlFor="quantity">Số lượng</label><div className="quantity"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Giảm số lượng">−</button><span>{quantity}</span><button onClick={() => setQuantity(quantity + 1)} aria-label="Tăng số lượng">+</button></div></div><button className="button button-primary add-button" disabled={product.stock === 0} onClick={() => setAdded(true)}>{added ? "Đã thêm vào giỏ mẫu ✓" : "Thêm vào giỏ hàng"}</button><div className="detail-note">Giao diện demo đang dùng dữ liệu mẫu. Giá và tồn kho sẽ kết nối API ở giai đoạn tích hợp.</div></div></div><section className="spec-section"><div><span className="eyebrow">Thông tin kỹ thuật</span><h2>Chi tiết được chọn.</h2></div><div className="spec-grid">{Object.entries(product.specs).map(([key, value]) => <div key={key}><span>{key}</span><strong>{value}</strong></div>)}</div></section></main><Footer /></>; }
