-- Lát cắt đầu tiên của T03: bảng hãng sản phẩm để kiểm tra Flyway và JPA.
CREATE TABLE brands (
    brand_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    logo_url VARCHAR(2048),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT ck_brands_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
