export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  oldPrice?: number;
  stock: number;
  description: string;
  specs: Record<string, string>;
  accent: string;
  badge?: string;
  featured?: boolean;
  rating?: number;
  reviewCount?: number;
  warranty?: string;
  images?: string[];
};

export const categories = [
  { name: "Laptop", count: "24 sản phẩm", tone: "violet" },
  { name: "PC Gaming", count: "18 sản phẩm", tone: "cyan" },
  { name: "Linh kiện", count: "96 sản phẩm", tone: "orange" },
  { name: "Phụ kiện", count: "42 sản phẩm", tone: "lime" },
];

export const brands = [
  "Tất cả",
  "ASUS",
  "GIGABYTE",
  "MSI",
  "Intel",
  "AMD",
  "Samsung",
  "Kingston",
  "Corsair",
  "LG",
  "Keychron",
  "PC Store",
];

export const products: Product[] = [
  {
    id: "p1",
    slug: "rog-strix-g16-2025",
    name: "ROG Strix G16 2025",
    brand: "ASUS",
    category: "Laptop",
    price: 38990000,
    oldPrice: 41990000,
    stock: 8,
    description: "Laptop gaming cân bằng giữa hiệu năng mạnh và kiểu dáng sắc gọn cho những phiên chơi dài.",
    specs: { CPU: "Intel Core Ultra 9", GPU: "RTX 5070 8GB", RAM: "32GB DDR5", SSD: "1TB NVMe", Screen: "16 inch · 240Hz" },
    accent: "#6f55ff",
    badge: "Mới về",
    featured: true,
    rating: 4.9,
    reviewCount: 38,
    warranty: "24 tháng chính hãng",
    images: ["Góc trước máy", "Bàn phím RGB", "Cổng kết nối", "Mặt lưng nhôm"],
  },
  {
    id: "p2",
    slug: "tuf-gaming-a15",
    name: "TUF Gaming A15",
    brand: "ASUS",
    category: "Laptop",
    price: 24990000,
    oldPrice: 27990000,
    stock: 5,
    description: "Thiết kế bền bỉ, màn hình nhanh và pin đủ lâu cho học tập lẫn gaming.",
    specs: { CPU: "Ryzen 7 8845HS", GPU: "RTX 4060 8GB", RAM: "16GB DDR5", SSD: "512GB NVMe", Screen: "15.6 inch · 144Hz" },
    accent: "#19b5fe",
    badge: "-11%",
    featured: true,
    rating: 4.7,
    reviewCount: 22,
    warranty: "24 tháng chính hãng",
    images: ["Mặt trước", "Bàn phím số", "Góc nghiêng tản nhiệt"],
  },
  {
    id: "p3",
    slug: "pc-creator-pro-x",
    name: "PC Creator Pro X",
    brand: "PC Store",
    category: "PC Gaming",
    price: 52990000,
    stock: 3,
    description: "Cỗ máy hiệu suất cao cho dựng phim, render và chơi game ở độ phân giải lớn.",
    specs: { CPU: "Core i9-14900K", GPU: "RTX 4080 Super", RAM: "64GB DDR5", SSD: "2TB NVMe", PSU: "850W Gold" },
    accent: "#ff6a3d",
    badge: "Bán chạy",
    featured: true,
    rating: 5.0,
    reviewCount: 15,
    warranty: "36 tháng tận nơi",
    images: ["Thùng máy kính cường lực", "Nội thất RGB", "Góc làm việc thực tế"],
  },
  {
    id: "p4",
    slug: "rtx-4070-super-dual",
    name: "RTX 4070 Super Dual",
    brand: "GIGABYTE",
    category: "Linh kiện",
    price: 16990000,
    stock: 12,
    description: "GPU mát, yên tĩnh và sẵn sàng cho game 1440p mượt mà với công nghệ DLSS 3.5.",
    specs: { Chip: "Ada Lovelace", VRAM: "12GB GDDR6X", Ports: "3x DP · 1x HDMI", Power: "650W" },
    accent: "#f5b700",
    rating: 4.8,
    reviewCount: 29,
    warranty: "36 tháng",
    images: ["Mặt quạt Windforce", "Backplate kim loại", "Hộp sản phẩm"],
  },
  {
    id: "p5",
    slug: "kingston-fury-32gb",
    name: "Kingston Fury 32GB",
    brand: "Kingston",
    category: "Linh kiện",
    price: 2190000,
    stock: 20,
    description: "Bộ nhớ DDR5 ổn định, tốc độ cao cho hệ thống đa nhiệm và gaming hiện đại.",
    specs: { Capacity: "32GB (2x16GB)", Speed: "DDR5-6000", Latency: "CL36", Warranty: "36 tháng" },
    accent: "#a5dc36",
    rating: 4.9,
    reviewCount: 45,
    warranty: "36 tháng",
    images: ["Cặp RAM tản đen", "Chi tiết chân cắm vàng"],
  },
  {
    id: "p6",
    slug: "ssd-nvme-990-pro",
    name: "990 Pro NVMe 2TB",
    brand: "Samsung",
    category: "Linh kiện",
    price: 4390000,
    oldPrice: 4990000,
    stock: 0,
    description: "Ổ cứng NVMe tốc độ đọc cao cho hệ điều hành và thư viện game nặng cần load tức thì.",
    specs: { Capacity: "2TB", Interface: "PCIe 4.0", Read: "7,450 MB/s", Warranty: "60 tháng" },
    accent: "#ec4899",
    badge: "Hết hàng",
    rating: 4.9,
    reviewCount: 64,
    warranty: "60 tháng",
    images: ["Thẻ NVMe M.2", "Tem kiểm định tốc độ"],
  },
  {
    id: "p7",
    slug: "mechanical-keyboard-k75",
    name: "Mechanical Keyboard K75",
    brand: "Keychron",
    category: "Phụ kiện",
    price: 2890000,
    stock: 9,
    description: "Bàn phím cơ compact với layout 75% và cảm giác gõ chắc tay, hỗ trợ hot-swap.",
    specs: { Layout: "75%", Switch: "K Pro Brown", Connection: "Tri-mode", Battery: "4000mAh" },
    accent: "#27c3a2",
    rating: 4.8,
    reviewCount: 31,
    warranty: "12 tháng",
    images: ["Tổng thể bàn phím", "Góc nghiêng núm xoay", "Phụ kiện đi kèm"],
  },
  {
    id: "p8",
    slug: "ultrawide-monitor-34",
    name: "Ultrawide Monitor 34",
    brand: "LG",
    category: "Phụ kiện",
    price: 11990000,
    stock: 4,
    description: "Không gian hiển thị rộng cho công việc sáng tạo và chơi game nhập vai sống động.",
    specs: { Size: "34 inch", Resolution: "3440 × 1440", Refresh: "165Hz", Panel: "IPS" },
    accent: "#3788ff",
    rating: 4.7,
    reviewCount: 19,
    warranty: "24 tháng",
    images: ["Màn hình cong", "Mặt lưng chân đế", "Không gian làm việc"],
  },
  {
    id: "p9",
    slug: "intel-core-i7-14700k",
    name: "Intel Core i7-14700K",
    brand: "Intel",
    category: "Linh kiện",
    price: 10490000,
    oldPrice: 11290000,
    stock: 14,
    description: "Bộ vi xử lý 20 nhân 28 luồng, cân tốt cả gaming đỉnh cao và tác vụ đồ họa nặng.",
    specs: { Socket: "LGA1700", Cores: "20 (8P + 12E)", Threads: "28", BaseClock: "3.4 GHz", BoostClock: "5.6 GHz" },
    accent: "#0071c5",
    badge: "Hot",
    featured: true,
    rating: 4.9,
    reviewCount: 52,
    warranty: "36 tháng",
    images: ["Hộp CPU Intel xanh", "Mặt IHS kim loại", "Mặt sau chân socket"],
  },
  {
    id: "p10",
    slug: "amd-ryzen-7-7800x3d",
    name: "AMD Ryzen 7 7800X3D",
    brand: "AMD",
    category: "Linh kiện",
    price: 10890000,
    stock: 7,
    description: "Vua gaming hiện tại với công nghệ 3D V-Cache dung lượng lớn giảm thiểu giật khung hình.",
    specs: { Socket: "AM5", Cores: "8", Threads: "16", BaseClock: "4.2 GHz", Cache: "96MB L3", TDP: "120W" },
    accent: "#ed1c24",
    badge: "Vua Gaming",
    featured: true,
    rating: 5.0,
    reviewCount: 88,
    warranty: "36 tháng",
    images: ["Hộp Ryzen đặc trưng", "Mặt lưng AM5", "Tem chính hãng"],
  },
  {
    id: "p11",
    slug: "mainboard-rog-strix-b760-f",
    name: "ROG STRIX B760-F Gaming WiFi",
    brand: "ASUS",
    category: "Linh kiện",
    price: 5690000,
    stock: 6,
    description: "Bo mạch chủ Intel B760 hỗ trợ DDR5, PCIe 5.0 và WiFi 6E tốc độ cao cho game thủ.",
    specs: { Socket: "LGA1700", FormFactor: "ATX", Memory: "4x DDR5 (Max 192GB)", PCIe: "PCIe 5.0 x16", Network: "WiFi 6E + 2.5GbE" },
    accent: "#6f55ff",
    rating: 4.8,
    reviewCount: 16,
    warranty: "36 tháng",
    images: ["Toàn cảnh bo mạch", "Khu vực tản VRM", "Cụm cổng I/O phía sau"],
  },
  {
    id: "p12",
    slug: "corsair-rm850e-gold",
    name: "Corsair RM850e 850W Gold",
    brand: "Corsair",
    category: "Linh kiện",
    price: 3290000,
    stock: 15,
    description: "Nguồn máy tính chuẩn ATX 3.0 với cáp PCIe 5.0 12VHPWR cho các thế hệ GPU mới nhất.",
    specs: { Wattage: "850W", Efficiency: "80 Plus Gold", Modular: "Full Modular", Standard: "ATX 3.0 & PCIe 5.0" },
    accent: "#f9a825",
    rating: 4.9,
    reviewCount: 41,
    warranty: "84 tháng chính hãng",
    images: ["Khung nguồn đen nhám", "Bộ dây cáp rời", "Mặt sau công tắc"],
  },
];

export function formatPrice(value: number) {
  return new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
    maximumFractionDigits: 0,
  }).format(value);
}

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
